name: Github Action Demo

on:
  issues:
    types: [opened]

jobs: 
  print_issue_title:
    runs-on: ubuntu-latest
    name: Print Issue Title
    steps:
    - run: echo "${{github.event.issue.title}}"
    
